services:
  users-service:
    container_name: fatal-cinema-users-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.production.local
    networks:
      - fatal-cinema

networks:
  fatal-cinema:
    external: true
